#include "stdafx.h"
#include "globals.h"
#include <time.h>

COLORREF WHITE = RGB(255, 255, 255);
COLORREF BLACK = RGB(0, 0, 0);
COLORREF RED = RGB(255, 0, 0);
COLORREF GREEN = RGB(0, 255, 0);
COLORREF BLUE = RGB(0, 0, 255);
COLORREF YELLOW = RGB(255, 255, 0);
COLORREF PURPLE = RGB(153, 50, 204);
COLORREF LIGHT_BLUE = RGB(30, 144, 255);
COLORREF ORANGE = RGB(250, 108, 10);

const int NUM_SQUARES_ACROSS = 10;
const int NUM_SQAURES_DOWN = 20;
const int MAIN_GRID_WIDTH = 320;
const int MAIN_GRID_HEIGHT = (NUM_SQAURES_DOWN/NUM_SQUARES_ACROSS)*MAIN_GRID_WIDTH;
const int SQ_SIZE = MAIN_GRID_WIDTH/NUM_SQUARES_ACROSS;
const int BORDER_WIDTH = 6;
const int GRID_WIDTH = BORDER_WIDTH/3;
const int OFFSET = SQ_SIZE;
